apiVersion: apps/v1
kind: Deployment
metadata:
  name: aoefou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aoefou
  template:
    metadata:
      labels:
        app: aoefou
    spec:
      containers:
      - image: okteto.dev/aoefou:latest
        name: aoefou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "03ef56d7-bc6e-485d-a221-72e5e988533a"
        - name: Vless_Path
          value: "/03ef56d7-bc6e-485d-a221-72e5e988533a"
        - name: Vmess_UUID
          value: "3e0c18e0-19f5-4683-85e3-99d659cdb7c2"
        - name: Vmess_Path
          value: "/3e0c18e0-19f5-4683-85e3-99d659cdb7c2"
        - name: Share_Path
          value: "/v2link"
